[package]
name = "password_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
sha2 = "0.10.9"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0.140"
arboard = "3.5.0"
image = "0.24"